[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
psephos = "DkCDEbhWqNUFto7AZQxvu2H5eiKV3whWEZDcPMqQeB4u"

[programs.devnet]
psephos = "DkCDEbhWqNUFto7AZQxvu2H5eiKV3whWEZDcPMqQeB4u"

[test.validator]
bind_address = "127.0.0.1"

[[test.genesis]]
address = "G616ZLAnrgeb7FrAvavozAyKmgzsuncz1XTvBYiUzh4H"
program = "/Users/cartel/development/solana/hackathons/privacy_hack/aztec/psephos/circuits/target/psephos_circuits.so"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 60000 tests/**/*.ts"
